export * from "./auth.service.js";
export * from "./course.service.js";
export * from "./student.service.js";
export * from "./teacher.service.js";
export * from "./assignement.service.js";
export * from "./google.service.js";
export * from "./homework.service.js";
export * from "./lessons.service.js";
export * from "./exams.service.js";
